"""
ml_regime.py — ML-Based Regime Classifier

Replaces the rule-based RegimeClassifier with a RandomForestClassifier
trained on a rolling 6-month window of labeled H1 bars.

Architecture
------------
Feature engineering:
  - ADX(14), ADX(28)
  - ATR% = ATR(14) / close
  - EMA50 slope (normalised)
  - EMA200 slope (normalised)
  - EMA50/EMA200 spread (normalised)
  - RSI(14)
  - Volatility ratio: ATR(5) / ATR(20)   — detects volatility spikes
  - Volume ratio: vol / rolling_50_vol    — institutional activity proxy
  - Day-of-week (sin/cos encoded)
  - Hour-of-day (sin/cos encoded)

Labels:
  Same 4-class enum as rule-based classifier (TRENDING/RANGING/VOLATILE/EVENT_DRIVEN).
  Initial labels generated by the rule-based RegimeClassifier on training data
  ("teacher model" bootstrapping). After 6 months live, labels can be updated
  using realised-return cross-entropy for each regime.

Training cadence:
  Re-trains every Sunday 22:00 UTC on the last 6 months of H1 bars.
  Falls back to rule-based RegimeClassifier if fewer than 500 labeled samples.

Drop-in interface:
  ml_clf.classify(h1_df, current_dt) → StrategyRegime
  Same signature as RegimeClassifier.classify() — swap in AdaptiveRouter.
"""

from __future__ import annotations

import logging
import pickle
from pathlib import Path
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd

from strategy.regime import RegimeClassifier, StrategyRegime

_log = logging.getLogger("strategy.adaptive")

_MIN_TRAIN_SAMPLES  = 500
_RETRAIN_HOURS      = 168   # 1 week
_MODEL_PATH         = Path("data/adaptive/ml_regime_model.pkl")
_FEATURE_NAMES = [
    "adx14", "adx28",
    "atr_pct",
    "ema50_slope", "ema200_slope", "ema_spread",
    "rsi14",
    "vol_ratio",        # ATR5 / ATR20
    "volume_ratio",     # vol / rolling50
    "dow_sin", "dow_cos",
    "hod_sin", "hod_cos",
]


# ---------------------------------------------------------------------------
# Feature engineering
# ---------------------------------------------------------------------------

def _wilder_smooth(series: pd.Series, period: int) -> pd.Series:
    return series.ewm(alpha=1.0 / period, adjust=False).mean()


def _compute_adx(df: pd.DataFrame, period: int = 14) -> pd.Series:
    high  = df["high"].astype(float)
    low   = df["low"].astype(float)
    close = df["close"].astype(float)

    tr    = pd.concat([
        high - low,
        (high - close.shift()).abs(),
        (low  - close.shift()).abs(),
    ], axis=1).max(axis=1)

    dm_p = (high.diff()).clip(lower=0)
    dm_m = (-low.diff()).clip(lower=0)
    mask = dm_p <= dm_m; dm_p[mask] = 0.0
    mask = dm_m <= dm_p.shift(fill_value=0); dm_m[mask] = 0.0

    atr_s  = _wilder_smooth(tr,   period)
    dmi_p  = 100.0 * _wilder_smooth(dm_p, period) / atr_s.replace(0, np.nan)
    dmi_m  = 100.0 * _wilder_smooth(dm_m, period) / atr_s.replace(0, np.nan)
    dx     = 100.0 * (dmi_p - dmi_m).abs() / (dmi_p + dmi_m).replace(0, np.nan)
    return _wilder_smooth(dx, period)


def _compute_rsi(close: pd.Series, period: int = 14) -> pd.Series:
    delta    = close.diff()
    avg_gain = delta.clip(lower=0).ewm(alpha=1.0 / period, adjust=False).mean()
    avg_loss = (-delta).clip(lower=0).ewm(alpha=1.0 / period, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0.0, np.nan)
    return 100.0 - (100.0 / (1.0 + rs))


def build_features(h1_df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert raw H1 OHLCV bars to a feature matrix.

    Parameters
    ----------
    h1_df : DataFrame with columns [open, high, low, close, volume]
            and a DatetimeTZAware index.

    Returns
    -------
    DataFrame with columns = _FEATURE_NAMES, aligned to h1_df index.
    Rows with NaN features are dropped (warmup period).
    """
    df = h1_df.copy()
    close  = df["close"].astype(float)
    volume = df["volume"].astype(float)

    # ADX
    df["adx14"] = _compute_adx(df, 14)
    df["adx28"] = _compute_adx(df, 28)

    # ATR %
    tr = pd.concat([
        df["high"] - df["low"],
        (df["high"] - close.shift()).abs(),
        (df["low"]  - close.shift()).abs(),
    ], axis=1).max(axis=1)
    atr14 = _wilder_smooth(tr, 14)
    atr5  = _wilder_smooth(tr, 5)
    atr20 = _wilder_smooth(tr, 20)
    df["atr_pct"]   = atr14 / close.replace(0, np.nan)
    df["vol_ratio"] = atr5  / atr20.replace(0, np.nan)

    # EMA slopes (normalised by price)
    ema50  = close.ewm(span=50,  adjust=False).mean()
    ema200 = close.ewm(span=200, adjust=False).mean()
    df["ema50_slope"]  = (ema50.diff()  / close.replace(0, np.nan))
    df["ema200_slope"] = (ema200.diff() / close.replace(0, np.nan))
    df["ema_spread"]   = (ema50 - ema200) / close.replace(0, np.nan)

    # RSI
    df["rsi14"] = _compute_rsi(close, 14)

    # Volume ratio
    vol_ma = volume.rolling(50, min_periods=10).mean()
    df["volume_ratio"] = volume / vol_ma.replace(0, np.nan)

    # Temporal features (sin/cos to preserve cyclicality)
    idx = df.index
    if hasattr(idx, "dayofweek"):
        dow = idx.dayofweek.values.astype(float)
        hod = idx.hour.values.astype(float) if hasattr(idx, "hour") else np.zeros(len(df))
    else:
        dow = np.zeros(len(df))
        hod = np.zeros(len(df))

    df["dow_sin"] = np.sin(2 * np.pi * dow / 7.0)
    df["dow_cos"] = np.cos(2 * np.pi * dow / 7.0)
    df["hod_sin"] = np.sin(2 * np.pi * hod / 24.0)
    df["hod_cos"] = np.cos(2 * np.pi * hod / 24.0)

    feat = df[_FEATURE_NAMES].replace([np.inf, -np.inf], np.nan).dropna()
    return feat


# ---------------------------------------------------------------------------
# Teacher model: labels from rule-based classifier
# ---------------------------------------------------------------------------

def label_with_teacher(h1_df: pd.DataFrame) -> pd.Series:
    """
    Generate training labels using the rule-based RegimeClassifier.

    Returns a Series of StrategyRegime values aligned to h1_df.index.
    """
    teacher = RegimeClassifier()
    labels = {}
    for i in range(50, len(h1_df)):
        window = h1_df.iloc[: i + 1]
        ts     = window.index[-1]
        try:
            dt = ts.to_pydatetime() if hasattr(ts, "to_pydatetime") else datetime.utcnow()
            labels[ts] = teacher.classify(window, dt)
        except Exception:
            labels[ts] = StrategyRegime.TRENDING
    return pd.Series(labels)


# ---------------------------------------------------------------------------
# MLRegimeClassifier
# ---------------------------------------------------------------------------

class MLRegimeClassifier:
    """
    Drop-in replacement for RegimeClassifier that uses a RandomForest model
    trained on rolling 6-month windows.

    Parameters
    ----------
    model_path : Path
        Where to persist/load the trained model.
    min_train_samples : int
        Minimum labeled bars required to train (else falls back to rule-based).
    retrain_hours : int
        Re-train every N hours of wall time.

    Usage
    -----
        clf = MLRegimeClassifier()
        clf.fit(h1_df)                    # initial fit (offline/startup)
        regime = clf.classify(h1_df, dt)  # same interface as RegimeClassifier
    """

    def __init__(
        self,
        model_path: Path = _MODEL_PATH,
        min_train_samples: int = _MIN_TRAIN_SAMPLES,
        retrain_hours: int = _RETRAIN_HOURS,
    ) -> None:
        self._model_path       = Path(model_path)
        self._min_samples      = min_train_samples
        self._retrain_hours    = retrain_hours
        self._model            = None
        self._fallback         = RegimeClassifier()
        self._last_trained_at: Optional[datetime] = None
        self._label_encoder    = {
            StrategyRegime.TRENDING:     0,
            StrategyRegime.RANGING:      1,
            StrategyRegime.VOLATILE:     2,
            StrategyRegime.EVENT_DRIVEN: 3,
        }
        self._label_decoder = {v: k for k, v in self._label_encoder.items()}

        # Load persisted model if present
        if self._model_path.exists():
            try:
                with open(self._model_path, "rb") as fh:
                    self._model = pickle.load(fh)
                _log.info("MLRegimeClassifier: loaded model from %s", self._model_path)
            except Exception as exc:
                _log.warning("MLRegimeClassifier: could not load model (%s), will retrain", exc)

    # ------------------------------------------------------------------
    # Public interface (drop-in for RegimeClassifier)
    # ------------------------------------------------------------------

    def classify(self, h1_df: pd.DataFrame, current_dt: datetime) -> StrategyRegime:
        """
        Classify the current regime.

        Falls back to rule-based RegimeClassifier if model not trained.
        """
        if self._model is None:
            return self._fallback.classify(h1_df, current_dt)

        try:
            feat = build_features(h1_df)
            if feat.empty:
                return self._fallback.classify(h1_df, current_dt)

            last_row = feat.iloc[[-1]].values
            pred = int(self._model.predict(last_row)[0])
            regime = self._label_decoder.get(pred, StrategyRegime.TRENDING)

            # Confidence check — if max_proba < 0.55 defer to fallback
            proba = self._model.predict_proba(last_row)[0]
            if proba.max() < 0.55:
                _log.debug("MLRegimeClassifier: low confidence (%.2f) → fallback", proba.max())
                return self._fallback.classify(h1_df, current_dt)

            _log.debug(
                "MLRegimeClassifier: %s (confidence=%.2f)",
                regime.value, proba.max()
            )
            return regime

        except Exception as exc:
            _log.warning("MLRegimeClassifier.classify error: %s", exc)
            return self._fallback.classify(h1_df, current_dt)

    def fit(self, h1_df: pd.DataFrame, force: bool = False) -> bool:
        """
        Train the RandomForest on h1_df.

        Parameters
        ----------
        h1_df : at least 500 bars of H1 OHLCV
        force : skip the retrain interval check

        Returns True if model was updated, False if skipped.
        """
        try:
            from sklearn.ensemble import RandomForestClassifier
            from sklearn.preprocessing import StandardScaler
            from sklearn.pipeline import Pipeline
        except ImportError:
            _log.error("MLRegimeClassifier: sklearn not installed — pip install scikit-learn")
            return False

        if not force and self._last_trained_at is not None:
            hours_since = (datetime.utcnow() - self._last_trained_at).total_seconds() / 3600
            if hours_since < self._retrain_hours:
                _log.debug("MLRegimeClassifier: skip retrain (%.1fh since last)", hours_since)
                return False

        _log.info("MLRegimeClassifier: starting fit on %d bars...", len(h1_df))

        try:
            features = build_features(h1_df)
            labels   = label_with_teacher(h1_df).reindex(features.index).dropna()
            features = features.loc[labels.index]

            if len(features) < self._min_samples:
                _log.warning(
                    "MLRegimeClassifier: only %d labeled samples (need %d) — skipping fit",
                    len(features), self._min_samples,
                )
                return False

            X = features.values
            y = labels.map(self._label_encoder).values

            model = Pipeline([
                ("scaler", StandardScaler()),
                ("rf", RandomForestClassifier(
                    n_estimators=200,
                    max_depth=8,
                    min_samples_leaf=20,
                    class_weight="balanced",
                    random_state=42,
                    n_jobs=-1,
                )),
            ])
            model.fit(X, y)

            # Persist
            self._model_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self._model_path, "wb") as fh:
                pickle.dump(model, fh)

            self._model          = model
            self._last_trained_at = datetime.utcnow()

            # Log class distribution
            unique, counts = np.unique(y, return_counts=True)
            dist = {self._label_decoder[int(u)].value: int(c) for u, c in zip(unique, counts)}
            _log.info("MLRegimeClassifier: fit complete. Classes: %s", dist)

            return True

        except Exception as exc:
            _log.error("MLRegimeClassifier.fit error: %s", exc, exc_info=True)
            return False

    def should_retrain(self) -> bool:
        """Return True if a retrain is due."""
        if self._last_trained_at is None:
            return True
        hours = (datetime.utcnow() - self._last_trained_at).total_seconds() / 3600
        return hours >= self._retrain_hours

    def feature_importances(self) -> Optional[pd.Series]:
        """Return feature importance Series, or None if not trained."""
        if self._model is None:
            return None
        try:
            rf    = self._model.named_steps["rf"]
            return pd.Series(rf.feature_importances_, index=_FEATURE_NAMES).sort_values(ascending=False)
        except Exception:
            return None
